### PR TITLE
Refactored double injection related code and tests into sub package

### PR DESCRIPTION
**Pull request by mrserverless**
Merged tests into single test suite with a single config.yml and shared packages.

Also:
- Removed test-config.yml and TestModule, to use hello-world.yml and HelloWorldModule
- Removed ConfigData (covered by JITDao) and HelloWorldConfig.otherData (unused)
- Removed InjectedEnvironmentCommandTest.test_simple_case() which is repeated.
- Added extra test in IntegrationTest to cater specifically eager singletons as per https://github.com/HubSpot/dropwizard-guice/issues/19

### CODE REVIEW

**Comment by oillio** [comment]
The merging of tests looks good.
Separating the injected commands is a good idea as well.  However, they are not really related to double injection.  Mind if we change the package name from **doubleinject** to **command**?

**Comment by mrserverless** [comment]
great, yep this has been renamed. Although the `InjectedConfiguredCommandTest` is still broken due to the injected `Environment` I added into `DependentModule`

**Comment by oillio** [comment]
Sorry it took me a while to get to this.  I wanted to fix the broken test before I merged it in.

I have fixed it by adding a check when modules are injected and dropping ones that fail injection (with a warning).  It is an imperfect solution.  If you hadn't injected the environment directly, and instead only had the eager singleton that depends on the environment it would still fail.  This is because the eager singleton will throw the exception when it is added to the injector, not when the module itself is injected.

I also worry that this will add confusion.  If someone tries to use data from that bundle when the command is called, it will fail in an unexpected place.

What do you think?  Is this an OK solution?

**Comment by mrserverless** [comment]
Didn't have internet for a few days. Yeah think it's good. Thanks for fixing/merging.

**Pull request merged**
